/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TProtocolFactory.h"
#import "TApplicationError.h"
#import "TProtocolError.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TBase.h"
#import "TAsyncTransport.h"
#import "TBaseClient.h"


@interface Call : NSObject <TBase, NSCoding, NSCopying> 

@property (strong, nonatomic) NSString * fromName;
@property (assign, nonatomic) BOOL fromNameIsSet;
- (void) unsetFromName;

@property (strong, nonatomic) NSString * toName;
@property (assign, nonatomic) BOOL toNameIsSet;
- (void) unsetToName;

@property (strong, nonatomic) NSString * fromUUID;
@property (assign, nonatomic) BOOL fromUUIDIsSet;
- (void) unsetFromUUID;

@property (strong, nonatomic) NSString * toUUID;
@property (assign, nonatomic) BOOL toUUIDIsSet;
- (void) unsetToUUID;


- (instancetype) initWithFromName: (NSString *) fromName toName: (NSString *) toName fromUUID: (NSString *) fromUUID toUUID: (NSString *) toUUID;

@end

@interface CallResult : NSObject <TBase, NSCoding, NSCopying> 

@property (strong, nonatomic) NSString * response;
@property (assign, nonatomic) BOOL responseIsSet;
- (void) unsetResponse;


- (instancetype) initWithResponse: (NSString *) response;

@end

@interface RegisterUserId : NSObject <TBase, NSCoding, NSCopying> 

@property (strong, nonatomic) NSString * userId;
@property (assign, nonatomic) BOOL userIdIsSet;
- (void) unsetUserId;

@property (strong, nonatomic) NSString * firebaseToken;
@property (assign, nonatomic) BOOL firebaseTokenIsSet;
- (void) unsetFirebaseToken;


- (instancetype) initWithUserId: (NSString *) userId firebaseToken: (NSString *) firebaseToken;

@end

@interface RegisterResult : NSObject <TBase, NSCoding, NSCopying> 

@property (strong, nonatomic) NSString * response;
@property (assign, nonatomic) BOOL responseIsSet;
- (void) unsetResponse;


- (instancetype) initWithResponse: (NSString *) response;

@end

@protocol Webrtc <NSObject>
- (CallResult *) call: (Call *) call error: (NSError *__autoreleasing *)__thriftError;  // throws TException
- (RegisterResult *) registerUserId: (RegisterUserId *) registerUserId error: (NSError *__autoreleasing *)__thriftError;  // throws TException
@end

@interface WebrtcClient : TBaseClient <Webrtc> 
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface WebrtcProcessor : NSObject <TProcessor> 
- (id) initWithWebrtc: (id <Webrtc>) service;
- (id<Webrtc>) service;
@end

FOUNDATION_EXPORT NSString *WebrtcErrorDomain;


